language: node_js
node_js:
  - "0.10"
install:
  - "npm install bower grunt-cli pulp@3.2.2 purescript mocha  -g"
  - "bower install -f"
  - "npm install mock-require"
script: 
  - "bash ./buildAndRunTests.sh"
